-- Migration 004: salary_records
-- One row per employee per pay period. Generated by POST /api/v1/payroll/generate.
-- This is a permanent snapshot — changing hourly_rate later never affects past records.
-- All values are aggregated from attendance_logs for the given date range.

DO $$ BEGIN
  CREATE TYPE salary_status AS ENUM ('draft', 'approved', 'paid');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS salary_records (
  id                    UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id           UUID           NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  period_start          DATE           NOT NULL,
  period_end            DATE           NOT NULL,
  total_days_present    INT            NOT NULL DEFAULT 0,
  total_days_absent     INT            NOT NULL DEFAULT 0,
  total_days_leave      INT            NOT NULL DEFAULT 0,
  total_days_late       INT            NOT NULL DEFAULT 0,
  total_days_half_day   INT            NOT NULL DEFAULT 0,
  total_hours           NUMERIC(7,2)   NOT NULL DEFAULT 0.00,
  overtime_hours        NUMERIC(7,2)   NOT NULL DEFAULT 0.00,
  base_pay              NUMERIC(12,2)  NOT NULL DEFAULT 0.00,
  total_overtime_pay    NUMERIC(12,2)  NOT NULL DEFAULT 0.00,
  total_deductions      NUMERIC(12,2)  NOT NULL DEFAULT 0.00,
  gross_pay             NUMERIC(12,2)  NOT NULL DEFAULT 0.00,
  net_pay               NUMERIC(12,2)  NOT NULL DEFAULT 0.00,
  hourly_rate_snapshot  NUMERIC(10,2)  NOT NULL,
  status                salary_status  NOT NULL DEFAULT 'draft',
  notes                 TEXT,
  generated_by          UUID           NOT NULL,
  approved_by           UUID,
  approved_at           TIMESTAMPTZ,
  paid_at               TIMESTAMPTZ,
  created_at            TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  CONSTRAINT salary_records_unique_period UNIQUE (employee_id, period_start, period_end),
  CONSTRAINT salary_records_period_order  CHECK (period_end >= period_start),
  CONSTRAINT salary_records_net_pay_check CHECK (net_pay >= 0)
);

CREATE INDEX IF NOT EXISTS salary_records_employee_id_idx ON salary_records (employee_id);
CREATE INDEX IF NOT EXISTS salary_records_period_idx      ON salary_records (period_start, period_end);
CREATE INDEX IF NOT EXISTS salary_records_status_idx      ON salary_records (status);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $func$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS salary_records_updated_at ON salary_records;
CREATE TRIGGER salary_records_updated_at
  BEFORE UPDATE ON salary_records
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();